### ISSUE TITLE
How to inject components in batches?

### ISSUE THREAD

**Issue by jiawade** [prashant-ramcharan/courgette-jvm-spring-example#2]
hello @prashant-ramcharan 
 I'am very new to spring, Suppose there are many components similar to TestSupport that need to be injected in classes. Do we need to manually write them one by one? Is there a way to inject them in batches?

@CucumberContextConfiguration
@SpringBootTest(classes = TestSupport.class)
public class TestSteps

**Comment by prashant-ramcharan** [comment]
Hello @jiawade , 

You will just need to create a Spring configuration class with `@ComponentScan`

This way you can simply annotate your classes with `@Component` `@Service` etc. and this will be available in the Spring app context.
